"""create user

Revision ID: fdee0f9d90f5
Revises: 047d6478390c
Create Date: 2022-09-21 23:30:12.332375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdee0f9d90f5'
down_revision = '047d6478390c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.add_column('operations', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'operations', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'operations', type_='foreignkey')
    op.drop_column('operations', 'user_id')
    op.drop_table('users')
    # ### end Alembic commands ###
